### ISSUE TITLE
Add decode_614a860c

### ISSUE THREAD

**Issue by t3ft3lb** [nao-sec/rr_decoder#3]
Please add decoding for signature {61 4A 86 0C}.
5.t Downloader sample from "memo to USARM release of documents to Vietnam.doc" https://www.virustotal.com/gui/file/ff35cfed656c0cac5571beae7170a2fec007e75417c1d0c4fd7af4185759ec38
![rr_sig_614A860C](https://github.com/nao-sec/rr_decoder/assets/82122521/b0863369-3c15-4f8b-9724-63075e2d9fac)

**Comment by koike** [comment]
Done!
https://github.com/nao-sec/rr_decoder/commit/c0096f9c87231caf637b10b8f94d8587eaed4462
