### ISSUE TITLE
Add decode_8291986F

### ISSUE THREAD

**Issue by t3ft3lb** [nao-sec/rr_decoder#4]
Please add decoding for signature {82 91 98 6F}.
5.t Downloader sample from the RTF file https://www.virustotal.com/gui/file/c16cdce72822bd40a5769811c36768147a3090438b1511fa01c68f7c51bd65c6
![rr_rtf](https://github.com/nao-sec/rr_decoder/assets/82122521/23df6bf7-c8bd-4187-8c62-6862121b6ab5)

**Comment by koike** [comment]
Done
https://github.com/nao-sec/rr_decoder/commit/618d797bbdddcecc9927c6b3851212685bcc44a2
